OpENer - Open Source EtherNet/IP(TM)  I/O Target Stack: src/cip/cipqos.c File Reference
cipqos.c File Reference
#include "cipqos.h"
#include "opener_user_conf.h"
#include "cipcommon.h"
#include "cipmessagerouter.h"
#include "ciperror.h"
#include "endianconv.h"
#include "cipethernetlink.h"
#include "opener_api.h"
#include "trace.h"
Data Structures
struct cip_qos_dscp_values
struct CipQosInstanceAttributes
Macros
#define DEFAULT_DSCP_EVENT 59u
#define DEFAULT_DSCP_EXPLICIT 27u
#define DEFAULT_DSCP_GENERAL 47u
#define DEFAULT_DSCP_HIGH 43u
#define DEFAULT_DSCP_LOW 31u
#define DEFAULT_DSCP_SCHEDULED 47u
#define DEFAULT_DSCP_URGENT 55u
Typedefs
typedef struct cip_qos_dscp_values CipQosDscpValues
Functions
CipUsint CipQosGetDscpPriority (ConnectionObjectPriority priority)
Initializing the data structures of the TCP/IP interface object.
EipStatus CipQoSInit ()
void CipQosResetAttributesToDefaultValues ()
Reset attribute values to default. Does not update currently used set.
void CipQosUpdateUsedSetQosValues ()
Updates the currently used set of DSCP priority values.
EipStatus GetAttributeSingleQoS (CipInstance *const RESTRICT instance, CipMessageRouterRequest *RESTRICT const message_router_request, CipMessageRouterResponse *RESTRICT const message_router_response, const struct sockaddr *originator_address, const int encapsulation_session)
void InitializeCipQos (CipClass *class)
EipStatus SetAttributeSingleQoS (CipInstance *instance, CipMessageRouterRequest *message_router_request, CipMessageRouterResponse *message_router_response, const struct sockaddr *originator_address, const int encapsulation_session)
Macro Definition Documentation
#define DEFAULT_DSCP_EVENT 59u
Definition at line 18 of file cipqos.c.
Referenced by CipQosResetAttributesToDefaultValues().
#define DEFAULT_DSCP_EXPLICIT 27u
Definition at line 24 of file cipqos.c.
Referenced by CipQosResetAttributesToDefaultValues().
#define DEFAULT_DSCP_GENERAL 47u
Definition at line 19 of file cipqos.c.
Referenced by CipQosResetAttributesToDefaultValues().
#define DEFAULT_DSCP_HIGH 43u
Definition at line 22 of file cipqos.c.
Referenced by CipQosResetAttributesToDefaultValues().
#define DEFAULT_DSCP_LOW 31u
Definition at line 23 of file cipqos.c.
Referenced by CipQosResetAttributesToDefaultValues().
#define DEFAULT_DSCP_SCHEDULED 47u
Definition at line 21 of file cipqos.c.
Referenced by CipQosResetAttributesToDefaultValues().
#define DEFAULT_DSCP_URGENT 55u
Definition at line 20 of file cipqos.c.
Referenced by CipQosResetAttributesToDefaultValues().
Typedef Documentation
typedef struct cip_qos_dscp_values CipQosDscpValues
Function Documentation
CipUsint CipQosGetDscpPriority (ConnectionObjectPriority priority)
Initializing the data structures of the TCP/IP interface object.
Definition at line 132 of file cipqos.c.
References cip_qos_dscp_values::dscp_explicit, cip_qos_dscp_values::dscp_high, cip_qos_dscp_values::dscp_low, cip_qos_dscp_values::dscp_scheduled, cip_qos_dscp_values::dscp_urgent, kConnectionObjectPriorityExplicit, kConnectionObjectPriorityHigh, kConnectionObjectPriorityLow, kConnectionObjectPriorityScheduled, and kConnectionObjectPriorityUrgent.
Referenced by CreateUdpSocket(), and NetworkHandlerInitialize().
EipStatus CipQoSInit (void)
Definition at line 159 of file cipqos.c.
References CreateCipClass(), cip_qos_dscp_values::dscp_event, cip_qos_dscp_values::dscp_explicit, cip_qos_dscp_values::dscp_general, cip_qos_dscp_values::dscp_high, cip_qos_dscp_values::dscp_low, cip_qos_dscp_values::dscp_scheduled, cip_qos_dscp_values::dscp_urgent, CipQosInstanceAttributes::dscp_values, GetAttributeSingleQoS(), GetCipInstance(), InitializeCipQos(), InsertAttribute(), InsertService(), kCipUsint, kEipStatusError, kEipStatusOk, kGetableSingle, kGetAttributeSingle, kNotSetOrGetable, kSetable, kSetAttributeSingle, CipQosInstanceAttributes::q_frames_enable, and SetAttributeSingleQoS().
Referenced by CipStackInit().
void CipQosResetAttributesToDefaultValues ()
Reset attribute values to default. Does not update currently used set.
Definition at line 234 of file cipqos.c.
References DEFAULT_DSCP_EVENT, DEFAULT_DSCP_EXPLICIT, DEFAULT_DSCP_GENERAL, DEFAULT_DSCP_HIGH, DEFAULT_DSCP_LOW, DEFAULT_DSCP_SCHEDULED, DEFAULT_DSCP_URGENT, cip_qos_dscp_values::dscp_event, and CipQosInstanceAttributes::dscp_values.
Referenced by ResetDeviceToInitialConfiguration().
void CipQosUpdateUsedSetQosValues ()
Updates the currently used set of DSCP priority values.
Definition at line 230 of file cipqos.c.
References CipQosInstanceAttributes::dscp_values.
Referenced by ResetDevice().
EipStatus GetAttributeSingleQoS (CipInstance *const RESTRICT instance, CipMessageRouterRequest *RESTRICT const message_router_request, CipMessageRouterResponse *RESTRICT const message_router_response, const struct sockaddr * originator_address, const int encapsulation_session)
Definition at line 70 of file cipqos.c.
References GetAttributeSingle().
Referenced by CipQoSInit().
void InitializeCipQos (CipClass * class)
Definition at line 156 of file cipqos.c.
Referenced by CipQoSInit().
EipStatus SetAttributeSingleQoS (CipInstance * instance, CipMessageRouterRequest * message_router_request, CipMessageRouterResponse * message_router_response, const struct sockaddr * originator_address, const int encapsulation_session)
Definition at line 82 of file cipqos.c.
References CipEpath::attribute_number, CalculateIndex(), cip_instance::cip_class, CipMessageRouterRequest::data, CipAttributeStruct::data, CipMessageRouterResponse::data_length, CipMessageRouterResponse::general_status, GetCipAttribute(), GetDintFromMessage(), kCipErrorAttributeNotSupported, kCipErrorInvalidAttributeValue, kCipErrorNotEnoughData, kCipErrorSuccess, kEipStatusOkSend, OPENER_TRACE_INFO, CipMessageRouterResponse::reply_service, CipMessageRouterRequest::request_path, CipMessageRouterRequest::service, cip_class::set_bit_mask, and CipMessageRouterResponse::size_of_additional_status.
Referenced by CipQoSInit().