OpENer - Open Source EtherNet/IP(TM)  I/O Target Stack: src/ports/networkhandler.h File Reference
networkhandler.h File Reference
#include "typedefs.h"
Macros
#define OPENER_SOCKET_WOULD_BLOCK EWOULDBLOCK
Functions
void CloseSocketPlatform (int socket_handle)
Platform dependent code to close a socket.
MicroSeconds GetMicroSeconds (void)
Returns current time in microseconds from monotonic time base, please note that this does not represent a real absolute time, but measured from an arbitrary starting point.
MilliSeconds GetMilliSeconds (void)
Returns current time in milliseconds from monotonic time base, please note that this does not represent a real absolute time, but measured from an arbitrary starting point.
EipStatus NetworkHandlerInitializePlatform (void)
Executes platform dependent network handler initialization code.
int SetQosOnSocket (const int socket, CipUsint qos_value)
Sets QoS on socket.
int SetSocketToNonBlocking (int socket_handle)
Tries to set socket to non blocking behavior.
void ShutdownSocketPlatform (int socket_handle)
Platform dependent code to shutdown a stream socket.
Macro Definition Documentation
#define OPENER_SOCKET_WOULD_BLOCK EWOULDBLOCK
Definition at line 11 of file networkhandler.h.
Referenced by CheckAndHandleConsumingUdpSockets(), and HandleDataOnTcpSocket().
Function Documentation
void CloseSocketPlatform (int socket_handle)
Platform dependent code to close a socket.
Parameters
socket_handle The socket handle to be closed
Definition at line 44 of file networkhandler.c.
Referenced by CloseSocket().
MicroSeconds GetMicroSeconds (void)
Returns current time in microseconds from monotonic time base, please note that this does not represent a real absolute time, but measured from an arbitrary starting point.
This function returns the current time relative to an arbitrary starting point from a monotonic time source. As monotonic clocks and clock functions in general are platform dependent, this has to be implemented for each platform (see ports subfolders)
Returns
Current time relative to monotonic clock starting point as MicroSeconds
Definition at line 22 of file networkhandler.c.
References OPENER_ASSERT.
Referenced by GetMilliSeconds().
MilliSeconds GetMilliSeconds (void)
Returns current time in milliseconds from monotonic time base, please note that this does not represent a real absolute time, but measured from an arbitrary starting point.
This function returns the current time relative to an arbitrary starting point from a monotonic time source. As monotonic clocks and clock functions in general are platform dependent, this has to be implemented for each platform (see ports subfolders)
Returns
Current time relative to monotonic clock starting point as MilliSeconds
Definition at line 28 of file networkhandler.c.
References getMicroSeconds(), and GetMicroSeconds().
Referenced by NetworkHandlerInitialize(), and NetworkHandlerProcessOnce().
EipStatus NetworkHandlerInitializePlatform (void)
Executes platform dependent network handler initialization code.
Returns
EipStatusOk if initialization was successful, otherwise EipStatusError
Definition at line 32 of file networkhandler.c.
References kEipStatusOk.
Referenced by NetworkHandlerInitialize().
int SetQosOnSocket (const int socket, CipUsint qos_value)
Sets QoS on socket.
A wrapper function - needs a platform dependent implementation to set QoS on a socket
Parameters
socket The socket which QoS shall be set
qos_value The desired QoS value, as specified in ENIP Vol.2 QoS Object
Returns
platform dependent result code
Definition at line 53 of file networkhandler.c.
Referenced by CreateUdpSocket(), and NetworkHandlerInitialize().
int SetSocketToNonBlocking (int socket_handle)
Tries to set socket to non blocking behavior.
Parameters
socket_handle The socket handle to be set
Returns
platform specific result code
Definition at line 48 of file networkhandler.c.
Referenced by CreateUdpSocket(), and NetworkHandlerInitialize().
void ShutdownSocketPlatform (int socket_handle)
Platform dependent code to shutdown a stream socket.
Parameters
socket_handle The socket to shut down
Definition at line 40 of file networkhandler.c.
References FreeErrorMessage(), GetErrorMessage(), GetSocketErrorNumber(), and OPENER_TRACE_ERR.
Referenced by CloseTcpSocket().